<?php

/**
 * @file
 * custom dashboard functionality to get pictures from HMS
 */

/**
 * Function called by block to get the image.
 */
function dashboard_picture_pic() {

  global $user;
  $account = user_load($user->uid);

  // Name for displaying as alt on image.
  $name = $account->field_first_name[LANGUAGE_NONE][0]['value'] . ' ' . $account->field_last_name[LANGUAGE_NONE][0]['value'];

  if (is_null($account->picture)) {
    $picture_data = dashboard_picture_get_picture('/sites/all/themes/oncampus_omega4/images/placeholder_icon_gold.png', $name);
  } else {
    $picture_data = dashboard_picture_get_picture($account->picture->uri, $name);
  }

  return $picture_data;

}

// Output profile or default picture to dashboard
function dashboard_picture_get_picture($pic_path, $name) {

  $pic_variables = array(
    'path' => $pic_path,
    'alt' => $name,
    'attributes' => array('class' => 'my-info-img', 'id' => 'my-info-img'),
  );

  $pic = theme('image', $pic_variables);
  return $pic;

}

function dashboard_picture_from_starrez($entryid, $uuid) {

  $base_url = variable_get('myroom_starrezz_end_point_url','http://128.138.29.213/starrezrestdevelopment/services/');
  $authname = variable_get('myroom_starrez_authname','hds\rehabcreative');
  $pw_raw = variable_get('myroom_starrez_authpw',FALSE);
  $auth_pw = $pw_raw ? myroom_starrez_ec_dc('decrypt', $pw_raw) : "unset";

  $document_root = $GLOBALS['_SERVER']['DOCUMENT_ROOT'];

  $source_url = $base_url.'photo/Entry/'.$entryid;
  $save_path = $document_root . '/sites/default/files/user_images/';
  $new_image = 'picture-' . $uuid . '-' . time('now') . '.jpg';
  $full_save_path = $save_path . $new_image;

  $ch = curl_init($source_url);
  curl_setopt($ch, CURLOPT_HEADER, 0);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_BINARYTRANSFER,1);

  watchdog('base-url-service-fragment-get-pic','base-url-'.$source_url);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER,TRUE);

  curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'StarRezUsername:'.$authname,
    'StarRezPassword:'.$auth_pw
  ));
  $response = curl_exec($ch);
  curl_close($ch);

  if($response !== FALSE) {

    if (file_exists($full_save_path)) {
     unlink($full_save_path);
    }

    $fp = fopen($full_save_path, 'x');

    fwrite($fp, $response);
    fclose($fp);

    if (($pic_data = file_get_contents($full_save_path)) &&
      ($pic = file_save_data($pic_data, 'public://pictures/' . $new_image, FILE_EXISTS_REPLACE))) {
        unlink($full_save_path);
        return $pic;
    }

  }

}
